export default{
	goods:[
		{
			name:'jiemian',
			text:'预售屈臣氏牌百分之100纯棉洁面巾卸妆一次性洗脸巾男女80片*4盒',
			address:'广东中山',
			type:'包邮',
			price:'536.00',
			onlinePrice:' 199.60',
			cover:'static/images/a01_big.jpg',
			poster:'static/images/b05_big.png',
			color:'#e8e8e8',
			images:[
				'./static/images/a01_big.jpg',
				'./static/images/a02_big.jpg',
				'./static/images/a03_big.jpg',
				'./static/images/a04_big.jpg',
				'./static/images/a05_big.jpg',
			],
			thumbnails:[
				'./static/images/a01.jpg',
				'./static/images/a02.jpg',
				'./static/images/a03.jpg',
				'./static/images/a04.jpg',
				'./static/images/a05.jpg',
			],
		},
		{
			poster:'static/images/nivea.jpg',
		},
		{
			poster:'static/images/fila.jpg',
		},
		{
			poster:'static/images/milk.jpg',
		}
	],
	nav:[
		{
			text:"美妆/彩妆",
			name:"美宝莲/MAC/卡拉泡泡"
		},
		{
			text:"日用品",
			name:"纸巾/牙膏"
		},
		{
			text:"护肤品",
			name:"悦木之源/倩碧/珂润/欧莱雅"
		},
		{
			text:"精美服饰",
			name:"女装/男装/儿童"
		},
		{
			text:"母婴用品",
			name:"纸尿裤/婴儿床"
		},
		{
			text:"鞋子",
			name:"男鞋/女鞋/靴子"
		},
	]
}